---
title: "p8105_hw3_fl2569"
author: "Fang Liu"
date: "10/15/2021"
output: html_document
---

```{r set_up}
#tidyverse pacakge (dplyr, ggplot2, etc)
library(tidyverse)

#figure size options
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

#set theme settings
theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1
This problem uses the Instacart (dataset_instacart.html) data. 

Write a short description of the dataset, noting the size and structure of the data, describing some key variables, and giving illustrative examples of observations. 

How many aisles are there, and which aisles are the most items ordered from?

Make a plot that shows the number of items ordered in each aisle, limiting this to aisles with more
than 10000 items ordered. Arrange aisles sensibly, and organize your plot so others can read it.

Make a table showing the three most popular items in each of the aisles “baking ingredients”,
“dog food care”, and “packaged vegetables fruits”. Include the number of times each item is
ordered in your table.

Make a table showing the mean hour of the day at which Pink Lady Apples and Coffee Ice Cream
are ordered on each day of the week; format this table for human readers (i.e. produce a 2 x 7
table).


## Problem 2

## Problem 3
